name: Build and Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer | node

      - name: Install deps
        run: pnpm i

      - name: Build website
        run: pnpm run build

      - name: Deploy website
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: flat-buster.de
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          local-dir: "./build/"
          protocol: "sftp"
